### ISSUE TITLE
The password reset tool linked from the reset page doesn't exist

### ISSUE THREAD

**Issue by klardotsh** [cblgh/cerca#56]
I managed to fail to copy my newly-generated password into Bitwarden before copying my new keypair - oops, lost clipboard state! So I needed to reset my password again, this time not using the logged-in flow.

The logged-out flow appears to be broken: the linked `https://github.com/cblgh/cerca/releases/tag/pwtool-v1` is a broken link, and I can't find a `pwtool` grepping around this repo anywhere to build it locally.

**Comment by cblgh** [comment]
@klardotsh hey sorry for the confusion! 

the long and short of it is i'm slowly migrating away from that approach because it ended up being too convoluted in practice. here's the commit removing the tool from the repo https://github.com/cblgh/cerca/commit/1257d66c5d9e851c555e38ac56cbd4d169b58708

it was useful as an intermediate step to allow myself to not collect email addresses as a password reset option. but as it turned out this particular approach didn't really work out for most users trying to reset their lost passwords and it introduced a lot of inutile complexity into the project, so away it went!
