### ISSUE TITLE
Private threads

### ISSUE THREAD

**Issue by decentral1se** [cblgh/cerca#64]
Heya 👋 Just checking in to see if this is a thing that would be considered for implementation? Threads that you can only view if you're logged in basically. For internal discussions. I don't see that option yet.

**Comment by cblgh** [comment]
yo @decentral1se! 

> Just checking in to see if this is a thing that would be considered for implementation? Threads that you can only view if you're logged in basically. For internal discussions. 

the answer is an emphatic *yes*! it's been on the bucket list since the start but, for various unimportant reasons, i haven't got around to it 

are you interested in teaming up to make it happen?

**Comment by decentral1se** [comment]
@cblgh cool! I am up for it 🎉 I do have 2 other things on my stack, but I've added this also 😌 If you're game for a braindump on how to take this forward? I'd be fairly new to it all ofc

**Comment by decentral1se** [comment]
That's lovely! Thanks for doing that work 💖 Would be Very Cool to get this done.

**Comment by cblgh** [comment]
alright, i've been stewing things over, mind dumpy text incoming! with this functionality we basically want to keep in mind two things:

* ensure that private threads are not visible without being logged in
* and exclude posts made to private threads from being visible in the rss feed

threads are normally served with the following url convention:

    /thread/<threadId>/<optional-thread-title-slug>

we then get the associated posts with `db.GetThread(threadId)` and populate a
template (thread.html, if viewing a thread) using the retrieved data.

before the rest comes on: feel free to start a branch and get whatever done of the below that you care to do! then, if you lose steam at some point, please feel free to make a pr to an equivalent branch on this repo and i can take it from there 😊💪

mini-guide for where everything is:

* [`html/`](https://github.com/cblgh/cerca/blob/main/html): the html templates 
* [`server/server.go`](https://github.com/cblgh/cerca/blob/main/server/server.go): http serving code & handlers
* [`database/database.go`](https://github.com/cblgh/cerca/blob/main/database/database.go): all the database handling code 
* [`database/migrations.go`](https://github.com/cblgh/cerca/blob/main/database/migrations.go): migrations, only one as of writing

back to the topic at hand! to facilitate private threads, perhaps we do the following:

in `database.go`:

* extend table `threads` with the column: `private INTEGER NOT NULL DEFAULT '0'` (which means we need a lil migration, more on that a bit further down)
* introduce `db.IsThreadPrivate(threadId)` to check if a given `threadId` is private or not
* change `db.ListThreads` to take an extra parameter `private bool` determining whether to include private threads in the returned listing

in `migrations.go`:

* add a new migration that alters table `threads` to have the new column. since there's a `default` value, all existing threads should be listed as not private

in `server.go`:

* extend `ThreadRoute` to be aware of private threads, using `db.IsThreadPrivate`
  and the local variable `loggedIn` / `h.isLoggedIn(req)`
* extend `NewThreadRoute` to be aware of private threads 
    * incl. handling a new form value determining whether the thread should be
      created as private or not
* adapt the `GenerateRSS` call to `db.ListThreads` to not query after private threads
* adapt the `IndexRoute` call to `db.ListThreads` to use the local variable `loggedIn` for
  determining whether to list all threads or only public threads

for user-facing feedback (so logged-in peeps know whether a thread is private or not), add changes to the following files in cerca's package `html` (it's golang html template files):

* `new-thread.html`: add a checkbox to send a new form value `isPrivate` (default value set to false)
* `thread.html`: add a `<p>` element right below the `<h1>` if it is a private thread: `this is a private thread, only logged-in users can see it and read its posts`, for example https://i.cblgh.org/2024-07/11450R1L.png
* `index.html`: add some indicator at the level of each listed thread title if it is a private thread. e.g. prefix the title with ⚿ ([U+26BF](http://www.fileformat.info/info/unicode/char/26bf/index.htm)). maybe something like this: https://i.cblgh.org/2024-07/1145440c.png not sure yet which of these is more preferable. fwiw i did the last version like this https://i.cblgh.org/2024-07/11455nlW.png

pardon if this was a bit much, but hopefully it's helpful in orienting and getting ones bearing for the codebase & this feature!

**Comment by decentral1se** [comment]
@cblgh https://github.com/cblgh/cerca/pull/66 ready for a review when time allows 🤓
