### ISSUE TITLE
Document how the RSS feed works

### ISSUE THREAD

**Issue by decentral1se** [cblgh/cerca#85]
It's chill and low-volume by design I would assume!

Is this written somewhere?

As I understand it, the logic is: the feed is per thread, only the latest poster will be shown of each thread. the feed is updated "in place". the feed will only be ever as long as the number of threads.

**Comment by cblgh** [comment]
> It's chill and low-volume by design I would assume!

yes!

> Is this written somewhere?

no!

> As I understand it, the logic is: the feed is per thread, only the latest poster will be shown of each thread. the feed is updated "in place". the feed will only be ever as long as the number of threads.

exactly!

it aims to kind of remind and guide people back to the forum. instead of having subscribers passively read every new post in one's rss reader, all that's shared is instead "this person made a post in this thread". so it acts more as a mid-tech notification feed? the idea is that being back in the forum increases the likelihood of someone forming a response / serendipitously seeing some other post and getting #inspired
