### ISSUE TITLE
Toggle thread privacy on edit?

### ISSUE THREAD

**Issue by decentral1se** [cblgh/cerca#90]
I assume this should be supported? I'm looking at updating the thread title. Just wanted to raise this here in case there are concerns about toggling this. Accidental Private -> Public might cause mayhem.

**Comment by cblgh** [comment]
so i'm going to be the weirdly opinionated software creator again and say that it is actually intentional. like you say, accidental private - public may cause mayhem. but *intentional* private -> public may cause mayhem. the people who contribute to a thread that is private do so on the terms that *it is private*. so imo the thread creator shouldn't have the power to expose the posts of those other folx?

taking a public thread and making it private has more going, like taking a thread that unfortunately was spicy into a community-only affair 

but ya that's the rationale and why it isn't implemented :~

**Comment by cblgh** [comment]
thanks for championing the documentation of these decisions @decentral1se, it is a great idea :]
